prefix = "hack-dev"
location = "eastus"
rg_name = "hack-stage-rg"
acr_name = "hackstageacr001"       # must be globally unique
aks_name = "hack-stage-aks"
keyvault_name = "hack-stage-kv"
tfstate_resource_group = "tfstate-rg"
tfstate_storage_account = "<TFSTATE_SA_NAME>"
tfstate_container = "tfstate"
